/**
 * Avellaneda-Stoikov Strategy Types
 *
 * Type definitions for the AS market making strategy
 */

/**
 * AS Model parameters
 */
export interface ASParameters {
  /**
   * Risk aversion parameter (gamma)
   * Higher values = more aggressive inventory targeting
   * Typical range: 0.1 - 1.0
   */
  gamma: number;

  /**
   * Order arrival intensity parameter (kappa)
   * Measures how sensitive order flow is to distance from mid price
   * Higher values = tighter optimal spreads
   * Typical range: 0.001 - 0.1
   */
  kappa: number;

  /**
   * Volatility (sigma)
   * Price volatility, calculated from historical data
   * Usually annualized, but can use any consistent time unit
   */
  sigma: number;

  /**
   * Time horizon (T)
   * Time remaining until trading session ends
   * In AS model: reservation price adjusts as T -> 0
   */
  timeHorizon: number;
}

/**
 * AS Strategy configuration
 * Extends base strategy config with AS-specific parameters
 */
export interface ASConfig {
  /** Strategy name */
  name: string;
  /** Trading symbol (e.g., BTCUSDT) */
  symbol: string;
  /** Quote asset (e.g., USDT) */
  quoteAsset: string;
  /** Base asset (e.g., BTC) */
  baseAsset: string;

  // ==================== Model Parameters ====================

  /**
   * Risk aversion parameter (gamma)
   * @default 0.5
   */
  gamma: number;

  /**
   * Order arrival intensity (kappa)
   * If not provided, will be calculated from market data
   * @default auto-calculated
   */
  kappa?: number;

  /**
   * Volatility (sigma)
   * If not provided, will be calculated from historical data
   * @default auto-calculated
   */
  sigma?: number;

  // ==================== Order Management ====================

  /** Base order size */
  orderSize: number;

  /**
   * Maximum spread multiplier
   * Limits how wide the spread can be (multiple of half-spread)
   * @default 3.0
   */
  maxSpreadMultiplier: number;

  /**
   * Minimum spread in absolute price terms
   * @default 0.01
   */
  minSpread: number;

  // ==================== Inventory Management ====================

  /** Maximum long position */
  maxPosition: number;

  /** Maximum short position (negative) */
  minPosition: number;

  /**
   * Target inventory level (usually 0 for market making)
   * @default 0
   */
  targetInventory: number;

  // ==================== Price Precision ====================

  /** Price tick size */
  tickSize: number;

  /** Lot size (minimum quantity step) */
  lotSize: number;

  // ==================== Execution ====================

  /**
   * Update interval in milliseconds
   * How often to recalculate and update orders
   * @default 1000
   */
  updateIntervalMs: number;

  /**
   * Volatility window - number of data points for sigma calculation
   * @default 100
   */
  volatilityWindow: number;

  /**
   * Kappa calculation window - number of order book snapshots
   * @default 50
   */
  kappaWindow: number;

  // ==================== Safety ====================

  /** Dry run mode - no actual orders placed */
  dryRun: boolean;

  /**
   * Emergency stop threshold
   * Stop strategy if unrealized PnL drops below this value
   * @default -1000
   */
  stopLossThreshold: number;
}

/**
 * Quote prices generated by AS model
 */
export interface ASQuote {
  /** Mid price */
  midPrice: number;

  /** Reservation price (adjusted for inventory) */
  reservationPrice: number;

  /** Optimal half spread */
  halfSpread: number;

  /** Bid price */
  bidPrice: number;

  /** Ask price */
  askPrice: number;

  /** Current inventory */
  inventory: number;

  /** Current gamma used */
  gamma: number;

  /** Current kappa used */
  kappa: number;

  /** Current sigma used */
  sigma: number;

  /** Timestamp */
  timestamp: number;
}

/**
 * AS Model state
 */
export interface ASState {
  /** Current inventory */
  inventory: number;

  /** Current mid price */
  midPrice: number;

  /** Current reservation price */
  reservationPrice: number;

  /** Current half spread */
  halfSpread: number;

  /** Current quotes */
  bidPrice: number;
  askPrice: number;

  /** Active orders */
  bidOrderId?: string;
  askOrderId?: string;

  /** Parameters used */
  parameters: ASParameters;
}

/**
 * Calculation result
 */
export interface ASCalculationResult {
  reservationPrice: number;
  halfSpread: number;
  bidPrice: number;
  askPrice: number;
  parameters: ASParameters;
}

/**
 * Volatility estimator configuration
 */
export interface VolatilityConfig {
  /** Window size for calculation */
  window: number;

  /** Use EWMA (Exponentially Weighted Moving Average) */
  useEwma: boolean;

  /** EWMA decay factor (0-1, higher = more weight on recent data) */
  ewmaDecay: number;
}

/**
 * Kappa estimator configuration
 */
export interface KappaConfig {
  /** Window size for calculation */
  window: number;

  /** Multiple of average spread to use for kappa estimation */
  spreadMultiplier: number;
}
